name: Test rules_mayhem Mayhemfiles

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
env:
  USE_BAZEL_VERSION: ${{ github.event.schedule != '' && 'last_green' || '' }}

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Mayhemfiles
        run: |
          bazel build //examples:factor_mayhemfile
          bazel build //examples:base64_mayhemfile
          bazel build //examples:lighttpd_mayhemfile
          bazel build //examples:package_mayhemit

      - name: Run tests
        run: |
          bazel test --test_output=all //examples:validate_factor
          bazel test --test_output=all //examples:validate_base64
          bazel test --test_output=all //examples:validate_lighttpd
          bazel test --test_output=all //examples:validate_mayhemit
