name: Test rules_mayhem Mayhemfiles

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
env:
  USE_BAZEL_VERSION: ${{ github.event.schedule != '' && 'last_green' || '' }}

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Get dependencies
        run: |
          sudo apt-get update && sudo apt-get install -yq \
            curl
      - name: Download Mayhem
        run: |
          curl --fail -L https://app.mayhem.security/cli/Linux/install.sh | sh
      - name: Build Mayhemfiles
        run: |
          bazel build //examples:all
      - name: Run tests
        run: |
          bazel test --test_output=all //examples:all
