name: Mayhem on Windows (Bazel-based)
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      mayhem_url:
        description: 'Mayhem URL'
        required: true
        default: 'https://app.mayhem.security'


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  MAYHEM_URL: ${{ github.event.inputs.mayhem_url || 'https://app.mayhem.security' }}
  MAYHEM_TOKEN: ${{ secrets.MAYHEM_TOKEN }}

jobs:
  build:
    name: '${{ matrix.os }} shared=${{ matrix.shared }} ${{ matrix.build_type }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        shared: [false]
        build_type: [Release]
        include:
          - os: windows-latest
            triplet: x64-windows

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prep Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Bazel
        uses: bazel-contrib/setup-bazel@0.8.5
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true

      - name: Create mayhem_secrets.bzl
        run: |
          echo "mayhem_url="""%MAYHEM_URL%"""" > mayhem_secrets.bzl
          echo "token="""%MAYHEM_TOKEN%"""" >> mayhem_secrets.bzl
        shell: cmd
        env:
          MAYHEM_URL: ${{ env.MAYHEM_URL }}
          MAYHEM_TOKEN: ${{ secrets.MAYHEM_TOKEN }}

      - name: Run bazel build
        run: |
          if not exist mayhem_secrets.bzl (
            echo "mayhem_secrets.bzl not found"
            exit /b 1
          )
          bazel build //examples:run_mayhemit
        shell: cmd
        env:
          MAYHEM_URL: ${{ env.MAYHEM_URL }}
          MAYHEM_TOKEN: ${{ secrets.MAYHEM_TOKEN }}
